config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'companies#index'

  get 'recenworks/:days' => 'works#index'

  get 'timetrackerproject/:slug' => 'projects#show'

      resources :companies
      resources :projects
      resources :works

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
	has_many :projects

	validates :name, length: { minimum: 5 }

	def to_s
		name
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :company
	has_many :works
	has_many :users, :through => :works
	belongs_to :owner, class_name: "User"

	validates :name, length: { minimum: 5 }
	validates :company_id, presence: true
	validates :owner_id, presence: true
	validates :default_rate, numericality: {only_integer: true,
											greater_than: 50,
											less_than: 10000}

	validates :slug, length: {minimum: 3}
	validates :slug, uniqueness: true

	scope :lowdefaultrate, -> {where("default_rate < 100")}

	def to_s
		"#{name} (#{company})"
	end

	def self.export_csv(projects)
		CSV.generate() do |csv|
			csv << ['name','company','default_rate','created_at','owner','most recent work item']
			projects.each do |project|
				csv << 	[
						project.name,
						project.company,
						project.default_rate,
						project.created_at,
						project.user,
						project.works.order('created_at DESC').first
						]
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	belongs_to :company
	has_many :works
	has_many :projects, :through => :works
	has_many :projects_owned, :foreign_key => 'owner_id', :class_name => 'Project'


	validates :fname, length: { minimum: 2 }
	validates :lname, length: { minimum: 5 }
	validates :company, presence: true

	def to_s
		"#{fname} #{lname}"
	end
end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :project
	belongs_to :user

	validates :project_id, presence: true
	validates :user_id, presence: true
	validates :datetimeperformed, presence: true
	validate :date_is_in_past
	validates :hours, numericality: { only_integer: true,
									  greater_than: 0,
									  less_than_or_equal_to: 8 }

	scope :fullday, -> { where("hours >= 8") }
	#scope :recent, -> {where("datetimeperormed > '#{Time.now - 7.days}'")}

	def self.recentdays(numdayago)
		since_date = Time.now - numdayago.to_i.days
		where("datetimeperformed > '#{since_date}'")
	end

	def date_is_in_past
		if datetimeperformed.present? && datetimeperformed > Time.now
			errors.add(:datetimeperformed, "can't be in the future")
		end
	end	

	def to_s
		"#{user}: #{datetimeperformed.strftime('%m/%d/%Y %H: %M')} - #{hours} hours"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'csv'
  protect_from_forgery with: :exception

def only_admins
	redirect_to root_path, :alert => 'Only admin' unless current_user.admin
end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]
	before_action :only_admins, except: [:index, :show]
	
	def index
		@companies = Company.all
	end

	def show
		@company = Company.find(params[:id])
			respond_to do |format|
				format.html # show.html.erb
				format.xml { render xml: @company}
				format.json { render json: @company}
			end
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(params[:company].permit(:name))
		if @company.save
			flash[:notice] = 'Company Created'
			redirect_to @company
		else
			render 'new'
		end
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(params[:company].permit(:name))
			flash[:notice] = 'Company Update'
			redirect_to @company
		else
			render 'edit'
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]

	def index
		@projects = Project.all
		respond_to do |format|
			format.html
			format.csv { send_data Project.export_csv(@projects), type: 'text/csv; charset=utf-8; header=present', disposition: 'attachment; filename=contacts.csv'}
		end
	end

	def show
		if (params[:slug])
			@project = Project.find_by slug: params[:slug]
		else
			@project = Project.find(params[:id])
		end
		@work = Work.new
		@work.project = @project
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project].permit(:name, :slug, :company_id, :default_rate))
		if @project.save
			flash[:notice] = 'Project Created'
			redirect_to @project
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(params[:project].permit(:name, :slug, :company_id, :default_rate))
			Usermailer.projectupdated_email(@project).deliver
			flash[:notice] = 'project Update'
			redirect_to @project
		else
			render 'edit'
		end
	end 
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]

	def index
		if (params[:days])
			@works = Work.recentdays(params[:days]).order('datetimeperformed desc').paginate(:page => params[:page])
		else
			@works = Work.all.order('datetimeperformed desc').paginate(:page => params[:page])
		end
	end

	def show
		@work = Work.find(params[:id])
	end

	def new
		@work = Work.new
	end

	def create
		@work = Work.new(params[:work].permit(:project_id, :datetimeperformed, :hours))
		@work.user = current_user
		if params[:doc]
			uploaded_io = params[:doc]
			File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
				file.write(uploaded_io.read)
				@work.doc = uploaded_io.original_filename
			end
		end
		respond_to do |format|
			if @work.save
				Usermailer.workcreated_email(@work).deliver
				format.html { redirect_to @work, notice: 'Work Created' }
				format.js {}
			else
				format.html { render 'new' }
				format.js {}
			end
		end
	end 

	def edit
		@work = Work.find(params[:id])
	end

	def update
		@work = Work.find(params[:id])
		@work.user = current_user
		if params[:doc]
			uploaded_io = params[:doc]
			File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
				file.write(uploaded_io.read)
				@work.doc = uploaded_io.original_filename
			end
		end
		if @work.update(params[:work].permit(:project_id, :datetimeperformed, :hours))
			flash[:notice] = 'Work Update'
			redirect_to @work
		else
			render 'edit'
		end
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper

	def nav_items
		[
			{
				displaytext: 'Companies',
				controllername: 'companies',
				linkurl: companies_path
			},
			{
				displaytext: 'Projects',
				controllername: 'projects',
				linkurl: projects_path
			},
			{
				displaytext: 'Works',
				controllername: 'works',
				linkurl: works_path
			}
		]
	end

	def display_nav_item(displaytext, controllername, linkurl)
		raw("<li#{controller_name == controllername ? ' class="active"' : ''}>#{link_to displaytext, linkurl}</li>")
	end		

	def user_logged_in_msg
		str = ''
		str += '<div class="userloggedin">'
		if user_signed_in?
			str += "<p id=""user_info"">#{current_user}<br>#{link_to('Logout', destroy_user_session_path, :method => :delete)}</p>"
		else
			str += "<p id=""user_info"">#{link_to('Login', new_user_session_path)} | #{link_to('Register', new_user_registration_path)}</p>"
		end
		str += '</div>'
		raw(str)
	end

	def sidebar
		unless ['sessions', 'registrations'].include?(controller_name)
			index_title = "All #{controller_name.capitalize}"
			index_path = "#{controller_name}_path"
			new_title = "New #{controller_name.singularize.capitalize}"
			new_path = "new_#{controller_name.singularize}_path"
			raw("<ul>
				<li>#{link_to index_title, eval(index_path)}</li>
				<li>#{link_to new_title, eval(new_path)}</li>
			</ul>")
		end
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/companies/_company.html.erb
<tr>
	<td><%= link_to company, company %></td>
</tr>

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
	<div id="errors">
		<p>Please correct the following <%= pluralize(@company.errors.count, "error") %>:</p>
		<ul>
			<% @company.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for(@company) do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.submit @company.new_record? ? "Create Company" : "Update Company" %>
	</div>
<% end %>

app/views/companies/_sidebar.html.erb
<ul>
	<li><%= link_to 'All Companies', companies_path %></li>
	<li><%= link_to 'New Company', new_company_path %></li>
</ul>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Companies: index</h1>

<p>Here are all of the companies:</p>

<table>
	<tbody>
		<tr>
			<th>Company</th>
		</tr>
		<%= render partial: "company", collection: @companies %>
	</tbody>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p><%= link_to 'Edit Company', edit_company_path(@company) %></p>

<% if @company.projects.size > 0 %>
<table>
	<tbody>
		<tr>
			<th>Project</th>
			<th>Company</th>
		</tr>
		<%= render partial: "projects/project", collection: @company.projects %>
	</tbody>
</table>
<% else %>
<p>No projects</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker1</title>
  <meta name="viewport" content="width=devise-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<header>
		<%= link_to content_tag('canvas', 'TimeTracker', id: 'logocanvas'), root_url %>
		<nav>
			<ul>
				<% nav_items.each do |nav_item| %>
					<%= display_nav_item(nav_item[:displaytext], nav_item[:controllername], nav_item[:linkurl])%>
				<% end %>
			</ul>
		</nav>
	</header>
	<section id="main">
		<article>
			<% [:notice, :alert].each do |level| %>
				<% if flash[level] %>
					<div class="flash <%= level %>"><%= flash[level] %></div>
				<% end %>
			<% end %>
			<%= yield %>
		</article>
		<aside>
			<%= user_logged_in_msg %>
			<% if content_for?(:aside) %>
				<%= yield :aside%>
			<% else %>
				<%= sidebar %>
			<% end %>
		</aside>
	</section>
	<footer>
		<p>Time Tracker is a <em>Sample Company</em> App</p>
	</footer>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
	<div id="errors">
		<p>Please correct the following <%= pluralize(@project.errors.count, "error") %>:</p>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for(@project) do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :slug %>
		<%= f.text_field :slug %>
	</div>
	<div>
		<%= f.label :default_rate %>
		<%= f.text_field :default_rate %>
	</div>
	<div>
		<%= f.label :company_id %>
		<%= f.collection_select(:company_id, Company.all, :id, :name, prompt: true) %>
	</div>
	<div>
		<%= f.label :owner_id %>
		<%= f.collection_select(:owner_id, User.all, :id, :to_s, prompt: true) %>
	</div>
	<div>
		<%= f.submit @project.new_record? ? "Create Project" : "Update Project" %>
	</div>
<% end %>

app/views/projects/_project.html.erb
		<tr>
			<td><%= link_to project, project %></td>
			<td><%= link_to project.company.name, project.company %></td>
		</tr>

app/views/projects/_sidebar.html.erb
<ul>
	<li><%= link_to 'All Projects', projects_path %></li>
	<li><%= link_to 'New Project', new_project_path %></li>
</ul>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects: index</h1>

<p>Here are all of the projects:</p>

<table>
	<tbody>
		<tr>
			<th>Project</th>
			<th>Company</th>
		</tr>
		<%= render partial: "project", collection: @projects %>
	</tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p>Company: <%= @project.company.name %></p>
<p>Default Rate: <%= @project.default_rate %></p>
<p>Slug: <%= @project.slug %></p>
<p>Owner: <%= @project.owner %></p>

<p><%= link_to "Edit Project", edit_project_path(@project) %></p>

<div class="remoteform">
	<h2>Add Work</h2>
	<%= render partial: 'works/form', locals: {doajax: true} %>
</div>

<% if @project.works.size > 0 %>
<table>
	<tbody>
		<tr id="headerrow">
			<th>View</th>
			<th>User</th>
			<th>Project</th>
			<th>Date/Time</th>
			<th>Hours</th>
		</tr>
		<%= render partial: "works/work", collection: @project.works %>
	</tbody>
</table>
<% else %>
<p>No work items</p>
<% end %>

app/views/works/_form.html.erb
<% if @work.errors.any? %>
	<div id="errors">
		<p>Please correct the following <%= pluralize(@work.errors.count, "error") %>:</p>
		<ul>
			<% @work.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<% doajax = false unless (defined? doajax) %>
<%= form_for(@work, remote: doajax, :html => {:multipart => true}) do |f| %>
	<div>
		<%= f.label :project_id %>
		<%= f.collection_select(:project_id, Project.all, :id, :name, prompt: true) %>
	</div>
	<div>
		<%= f.label :datetimeperformed, 'Date/Time Performed' %>
		<%= f.datetime_select :datetimeperformed %>
	</div>
	<div>
		<%= f.label :hours %>
		<%= f.select(:hours, [1,2,3,4,5,6,7,8], prompt: true) %>
	</div>
	<div>
		<%= label_tag :doc, 'Notes (optional)' %>
		<%= file_field_tag :doc %>
	</div>
	<div>
		<%= f.submit @work.new_record? ? "Create Work" : "Update Work" %>
	</div>
<% end %>

app/views/works/_sidebar.html.erb
<ul>
	<li><%= link_to 'All Works', works_path %></li>
	<li><%= link_to 'New Work', new_work_path %></li>
</ul>

app/views/works/_work.html.erb
		<tr>
			<td><%= link_to 'View', work %></td>
			<td><%= work.user %></td>
			<td><%= link_to work.project, work.project %></td>
			<td><%= work.datetimeperformed.strftime('%m/%d/%Y/ %H:%M') %></td>
			<td><%= work.hours %></td>
		</tr>

app/views/works/create.js.erb
<% if @work.errors.any? %>
	$('<div id="errors"><p>Please correct the following <%= pluralize(@work.errors.count, "error") %>:</p><ul><% @work.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %></ul></div>').insertBefore('div.remoteform h2');
<% else %>
	$('div#errors').remove();
	$('<tr><td><%= link_to 'View', @work %></td><td><%= @work.user %></td><td><%= link_to @work.project, @work.project %></td><td><%= @work.datetimeperformed.strftime("%m/%d/%Y %H:%M") %></td><td><%= @work.hours %></td></tr>').insertAfter('tr#headerrow');
<% end %>

app/views/works/edit.html.erb
<h1>Edit Work</h1>

<%= render 'form' %>

app/views/works/index.html.erb
<h1>Works: index</h1>

<p>Here are all of the works:</p>

<table>
	<tbody>
		<tr>
			<th>View</th>
			<th>User</th>
			<th>Project</th>
			<th>Date/Time</th>
			<th>Hours</th>
		</tr>
		<%= render partial: "work", collection: @works %>
	</tbody>
</table>

<%= will_paginate @work %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

app/views/works/show.html.erb
<h1><%= @work.datetimeperformed %></h1>

<p>User: <%= @work.user.fname %> <%= @work.user.lname %></p>
<p>Project: <%= @work.project.name %></p>
<p>Hours: <%= @work.hours %></p>

<% if @work.doc %>
	<p>Document: <%= link_to @work.doc, "/uploads/#{@work.doc}", :target => "_blank" %></p>
<% end %>

<p><%= link_to 'Edit Work', edit_work_path(@work) %></p>